version: '2'
services:
  jenkins-master1:
    privileged: true
    image: jenkins/jenkins:lts
    stdin_open: true
    network_mode: bridge
    volumes:
    - /Users/ahamadi/Desktop/Rancher_Presentation/rancher_1/jenkins/data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock:rw
    - /usr/local/bin/docker:/usr/bin/docker
    tty: true
    ports:
    - 8081:8080/tcp
    - 50001:50000/tcp
    labels:
      io.rancher.container.pull_image: always
